<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonglePet.Packages\MonglePet.Packages.csproj" />
    <ProjectReference Include="..\MonglePet.Settings\MonglePet.Settings.csproj" />
  </ItemGroup>

</Project>
